//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public string DivisionCode { get; set; }
        public string Division1 { get; set; }
        public System.DateTime DefinitionDate { get; set; }
        public Nullable<long> GUID { get; set; }
    }
}
