//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedReference
    {
        public long RecordNo { get; set; }
        public string GenFrom { get; set; }
        public string FormName { get; set; }
        public string FromBranchCode { get; set; }
        public string TransactionNature { get; set; }
        public string TransactionNo { get; set; }
        public string BranchCode { get; set; }
        public string DocumentNature { get; set; }
        public string DocumentNo { get; set; }
    }
}
