//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryTransactionAudit
    {
        public long RecordNo { get; set; }
        public string UserID { get; set; }
        public string ComputerID { get; set; }
        public System.DateTime ProcessDateTime { get; set; }
        public string Error { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string DocumentNature { get; set; }
        public string TransactionNo { get; set; }
        public long PartyCode { get; set; }
        public long ItemCode { get; set; }
        public decimal Quantity { get; set; }
        public decimal AvailableQuantity { get; set; }
        public decimal BalanceQuantity { get; set; }
    }
}
