//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.CustomerBillDetails = new HashSet<CustomerBillDetail>();
        }
    
        public string BranchCode { get; set; }
        public string TransactionNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string CustomerReference { get; set; }
        public string Description { get; set; }
        public string PartyCode { get; set; }
        public string VehicleCode { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string StationPointCode { get; set; }
        public string DestinationPointCode { get; set; }
        public string ProductCode { get; set; }
        public string TripAdvanceReference { get; set; }
        public Nullable<decimal> TripAdvance { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<int> CommissionRate { get; set; }
        public Nullable<decimal> ShortageQuantity { get; set; }
        public Nullable<decimal> QuantityValue { get; set; }
        public Nullable<decimal> Shortage { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<bool> Posted { get; set; }
        public long RecordNo { get; set; }
        public int GUID { get; set; }
        public Nullable<bool> IsTripCanceled { get; set; }
        public Nullable<byte> IsBilled { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBillDetail> CustomerBillDetails { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DestinationPoint DestinationPoint { get; set; }
        public virtual StationPoint StationPoint { get; set; }
        public virtual StationPoint StationPoint1 { get; set; }
        public virtual Product Product { get; set; }
        public virtual Vehicles_ Vehicles_ { get; set; }
    }
}
