//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayableAccount
    {
        public long BranchCode { get; set; }
        public long DocumentNature { get; set; }
        public string DocumentNo { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public long PartyCode { get; set; }
        public string MiscPartyName { get; set; }
        public string PartyReference { get; set; }
        public Nullable<System.DateTime> PartyReferenceDate { get; set; }
        public string InternalReference { get; set; }
        public Nullable<System.DateTime> InternalReferenceDate { get; set; }
        public string Description { get; set; }
        public int CreditDays { get; set; }
        public bool Locked { get; set; }
        public bool Posted { get; set; }
        public long RecordNo { get; set; }
        public long GUID { get; set; }
        public string OldRef { get; set; }
        public string RefNo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
