//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentVoucherDetail
    {
        public string BranchCode { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherNature { get; set; }
        public string APVNo { get; set; }
        public long APVNatureCode { get; set; }
        public int RecordNo { get; set; }
        public string SupplierBillNo { get; set; }
        public decimal APVAmount { get; set; }
        public long PaymentTypeCode { get; set; }
        public decimal TaxRate { get; set; }
        public decimal TaxValue { get; set; }
        public Nullable<long> GLCode { get; set; }
        public Nullable<long> DivisionCode { get; set; }
        public string OldRef { get; set; }
    }
}
