//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentVoucher
    {
        public string BranchCode { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherNature { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string TransactionTypeCode { get; set; }
        public string SupplierCode { get; set; }
        public string MiscPartyName { get; set; }
        public string CreditAccountCode { get; set; }
        public string CreditAccountReference { get; set; }
        public string Narration { get; set; }
        public long PaymentBankCode { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string TaxChallanNo { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public bool Locked { get; set; }
        public bool Posted { get; set; }
        public long RecordNo { get; set; }
        public long GUID { get; set; }
        public string OldRef { get; set; }
        public string RecordCreator { get; set; }
        public string RecordOwner { get; set; }
    }
}
