//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectNodesSetup
    {
        public long RecordNo { get; set; }
        public string NodeName { get; set; }
        public string TableName { get; set; }
        public string TableNature { get; set; }
        public string NodeType { get; set; }
        public byte ShowNode { get; set; }
        public int ImageIndex { get; set; }
        public Nullable<int> SortingOrder { get; set; }
        public string SystemType { get; set; }
    }
}
