//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class QryOtherAmountExcInvoice
    {
        public string VoucherNature { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string GLCode { get; set; }
        public string GLDescription { get; set; }
        public string Expr1 { get; set; }
        public System.DateTime VoucherDate { get; set; }
    }
}
