//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupTable
    {
        public string TableName { get; set; }
        public string AlternateTable { get; set; }
        public string TableNature { get; set; }
        public string TableType { get; set; }
        public Nullable<byte> ShowTable { get; set; }
        public int ss { get; set; }
    }
}
