//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTransDetailVBill
    {
        public string MODE { get; set; }
        public string TransactionNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public long RecordNo { get; set; }
        public string CustomerReference { get; set; }
        public string VehicleCode { get; set; }
        public string StationPointCode { get; set; }
        public string DestinationPointCode { get; set; }
        public string ProductCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> ShortageQuantity { get; set; }
        public Nullable<decimal> Shortage { get; set; }
        public Nullable<decimal> QuantityValue { get; set; }
        public string OwnerCode { get; set; }
        public string OwnerName { get; set; }
        public string UrduOwnerName { get; set; }
        public string ProductUrdu { get; set; }
        public string StationPointName { get; set; }
        public string StationPointUrdu { get; set; }
        public string DestinationPointName { get; set; }
        public string DestinationPointUrdu { get; set; }
        public string GLCode { get; set; }
        public string GLDescription { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string UrduCustomerName { get; set; }
        public string Capacity { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> TripAdvance { get; set; }
    }
}
