//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTransDetailTrialFSF
    {
        public string BranchCode { get; set; }
        public string BranchRptTitle { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionRptTitle { get; set; }
        public string GLCode { get; set; }
        public string GLRptTitle { get; set; }
        public string ControlCode { get; set; }
        public string ControlRptTitle { get; set; }
        public string GeneralCode { get; set; }
        public string GeneralRptTitle { get; set; }
        public string SubSidiaryCode { get; set; }
        public string SubsidiaryRptTitle { get; set; }
        public string SubsubCode { get; set; }
        public string SubSubRptTitle { get; set; }
        public string FSFGLCode { get; set; }
        public string FSFGLRptTitle { get; set; }
        public string FSFControlCode { get; set; }
        public string FSFControlRptTitle { get; set; }
        public string FSFGeneralCode { get; set; }
        public string FSFGeneralRptTitle { get; set; }
        public string FSFSubSidiaryCode { get; set; }
        public string FSFSubsidiaryRptTitle { get; set; }
        public string FSFSubsubCode { get; set; }
        public string FSFSubSubRptTitle { get; set; }
        public int OpeningBalance { get; set; }
        public Nullable<decimal> DebitBalance { get; set; }
        public Nullable<decimal> CreditBalance { get; set; }
    }
}
