//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTransDetailLedger
    {
        public string BranchCode { get; set; }
        public string BranchRptTitle { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionRptTitle { get; set; }
        public string GLCode { get; set; }
        public string GLRptTitle { get; set; }
        public string NatureCode { get; set; }
        public string NatureRptTitle { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string VoucherNo { get; set; }
        public string OldRef { get; set; }
        public string Narration { get; set; }
        public string NarrationMain { get; set; }
        public long RecordNo { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string ControlCode { get; set; }
        public string ControlRptTitle { get; set; }
        public string GeneralCode { get; set; }
        public string GeneralRptTitle { get; set; }
        public string SubSidiaryCode { get; set; }
        public string SubsidiaryRptTitle { get; set; }
        public string SubsubCode { get; set; }
        public string SubSubRptTitle { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<bool> Locked { get; set; }
        public long DetailRecordNo { get; set; }
        public string RefNo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
