//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionActivity
    {
        public long GUID { get; set; }
        public long ParentGUID { get; set; }
        public int FormTypeCode { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionTime { get; set; }
        public string UserID { get; set; }
        public string ComputerID { get; set; }
        public string ActionPerformed { get; set; }
        public string ReferenceText { get; set; }
    }
}
