//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionType()
        {
            this.VehicleAdjustmentDetails = new HashSet<VehicleAdjustmentDetail>();
            this.VehicleAdjustmentDetails1 = new HashSet<VehicleAdjustmentDetail>();
            this.InvoiceExpences = new HashSet<InvoiceExpence>();
            this.InvoiceExpences1 = new HashSet<InvoiceExpence>();
        }
    
        public string TransactionTypeCode { get; set; }
        public string TransactionType1 { get; set; }
        public string UrduTitle { get; set; }
        public Nullable<System.DateTime> DefinitionDate { get; set; }
        public string Nature { get; set; }
        public string GLCode { get; set; }
        public Nullable<byte> IsTripExpence { get; set; }
        public string RefNo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual TransactionNature TransactionNature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleAdjustmentDetail> VehicleAdjustmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleAdjustmentDetail> VehicleAdjustmentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceExpence> InvoiceExpences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceExpence> InvoiceExpences1 { get; set; }
    }
}
