//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleOwner()
        {
            this.Vehicles_ = new HashSet<Vehicles_>();
        }
    
        public string OwnerCode { get; set; }
        public string OwnerName { get; set; }
        public string UrduTitle { get; set; }
        public string Address { get; set; }
        public string CityCode { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string eMail { get; set; }
        public System.DateTime DefinitionDate { get; set; }
        public long GUID { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicles_> Vehicles_ { get; set; }
    }
}
