//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Invoices = new HashSet<Invoice>();
            this.VehicleAdjustments = new HashSet<VehicleAdjustment>();
        }
    
        public string VehicleCode { get; set; }
        public string VehicleDescription { get; set; }
        public string UrduTitle { get; set; }
        public string Capacity { get; set; }
        public string OwnerCode { get; set; }
        public string CustomerCode { get; set; }
        public string InstallmentGLCode { get; set; }
        public string FreightGLCode { get; set; }
        public string LoanGLCode { get; set; }
        public string CommissionGLCode { get; set; }
        public System.DateTime DefinitionDate { get; set; }
        public Nullable<bool> IsThirdParty { get; set; }
        public string DivisionCode { get; set; }
        public Nullable<long> GUID { get; set; }
        public string RefNo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleAdjustment> VehicleAdjustments { get; set; }
        public virtual VehicleOwner VehicleOwner { get; set; }
    }
}
