//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW3
    {
        public string VehicleCode { get; set; }
        public string VehicleDescription { get; set; }
        public System.DateTime DefinitionDate { get; set; }
        public string InstallmentGLCode { get; set; }
        public string InstallmentGLDescription { get; set; }
        public string FreightGLCode { get; set; }
        public string FreightGLDescription { get; set; }
        public string LoanGLCode { get; set; }
        public string LoanGLDescription { get; set; }
        public string OwnerCode { get; set; }
        public string OwnerName { get; set; }
        public string CommissionGLCode { get; set; }
        public string CommissionGLDescription { get; set; }
    }
}
