//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Integration.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherDetail
    {
        public string BranchCode { get; set; }
        public string VoucherNature { get; set; }
        public string VoucherNo { get; set; }
        public string GLCode { get; set; }
        public string DivisionCode { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Narration { get; set; }
        public long RecordNo { get; set; }
        public string RefNo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Voucher Voucher { get; set; }
    }
}
